### ISSUE TITLE
Fix Horizontal Scrolling Problem on Landing Page

### ISSUE THREAD

**Issue by SohaibaQ** [stakater/StakaterFrontend#19]

**Comment by ahmadiq** [comment]
The issue still occurs on google chrome browser

**Comment by ahmadiq** [comment]
I can still see the issue on chrome Version 63.0.3239.108 on Ubuntu 16.04

**Comment by ahmadiq** [comment]
Effort Estimate: 0.5 hr

**Comment by ahmadiq** [comment]
Closing this. Tracking on Jira now.
