### ISSUE TITLE
Fix css styles for alternating sections

### ISSUE THREAD

**Issue by ahmadiq** [stakater/StakaterFrontend#66]
The sections should have alternate background colours of white and blue as in the following image, and not gray and blue:
https://drive.google.com/a/aurorasolutions.io/file/d/151ZFqKcuo-Xx7alh1bc1n3Cp62SEPiMt/view?usp=sharing

you can also verify if this is the case in the psd: https://drive.google.com/a/aurorasolutions.io/file/d/1Q1c5Oeg0f00T1QVyxPKf72TvE-29ZOew/view?usp=sharing

Also, convert the section background styles of the page into two styles so that they can be used in alternating sections easily, and sections can be removed or add easily by just using some odd* and even* class names.

**Comment by ahmadiq** [comment]
@zainzafar90 the sections should have alternate background colours of white and blue as in the following image, and not gray and blue:
https://drive.google.com/a/aurorasolutions.io/file/d/151ZFqKcuo-Xx7alh1bc1n3Cp62SEPiMt/view?usp=sharing

you can also verify if this is the case in the psd: https://drive.google.com/a/aurorasolutions.io/file/d/1Q1c5Oeg0f00T1QVyxPKf72TvE-29ZOew/view?usp=sharing

**Comment by ZunairaT** [comment]
For alternate white sections, wrap them in bg-skewed class and the content inside those sections in bg-skewed-content class.

Whenever a new section is added, move the footer-group content inside the bg-skewed-content div of the last section.
